name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build and Generate Static Nuxt App
        run: yarn generate

      - name: Determine Environment (Production/Preview)
        id: environment
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" || $GITHUB_REF == "refs/heads/master" ]]; then
            echo "::set-output name=environment::production"
          else
            echo "::set-output name=environment::preview"
          fi

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: YOUR_PROJECT_NAME
          directory: dist # Nuxt.js static generate outputs to 'dist' directory
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ steps.environment.outputs.environment }}
